Feature: add the ability to update user email by superadmin
openware/barong pull request #1181
Opened 2020-12-03 10:18 UTC by akushniruk

2020-12-03 10:27 UTC, chumaknadya requested changes

2020-12-03 10:27 UTC, chumaknadya commented on app/api/v2/admin/users.rb
> +            exactly_one_of :state, :otp, :email, message: 'admin.user.one_of_state_otp'
message 'admin.user.one_of_state_otp_email'

2020-12-03 10:27 UTC, chumaknadya commented on spec/api/v2/admin/users_spec.rb
> +      end
check case when you will have `superadmin.user.update_email` error

2020-12-03 10:27 UTC, chumaknadya commented on spec/api/v2/admin/users_spec.rb
> +        end
check if email changed

2020-12-04 14:36 UTC, mod approved these changes

2020-12-04 14:39 UTC, chumaknadya approved these changes

2020-12-04 14:40 UTC, merged