Feature: Add IP country for admin user activities api
openware/barong pull request #1217
Opened 2021-01-06 07:01 UTC by jengjeng

Add IP country for admin user activities API.
This feature related to display IP country on the user activities page in Tower.

2021-01-11 09:01 UTC, chumaknadya approved these changes

2021-01-15 13:10 UTC, chumaknadya requested changes

2021-01-15 13:10 UTC, chumaknadya commented on app/api/v2/admin/entities/activity_with_user.rb
> +      expose :user_ip_country, documentation: { type: 'String' } do |activity|
Let's add new field for the activity table, where we will define user_ip_country

2021-03-10 14:15 UTC, josadcha commented
hello @jengjeng 
Would be nice to have this PR finished, because we just found out that Tower doesn't display info about country at all. Just a kind reminder for you.

2021-04-07 10:06 UTC, closed without merging