WIP: Setup auth0
openware/barong pull request #1222
Opened 2021-01-18 05:00 UTC by xenirio

TODO:
- [ ] Implement auth0 callback endpoint.
- [ ] Generate barong JWT after auth0 verified.

2021-01-18 08:48 UTC, chumaknadya requested changes

2021-01-18 08:48 UTC, chumaknadya commented on config/secrets.yml
> +  auth0_domain: openware-barong.us.auth0.com
you should do it on https://github.com/openware/barong/blob/master/config/initializers/barong.rb file

2021-01-18 08:48 UTC, chumaknadya commented on app/api/v2/base.rb
> +    mount Auth0::Base => '/auth0'
I think you dont need to create new module
For identity we have https://github.com/openware/barong/blob/master/app/api/v2/identity/sessions.rb this one
just create a namespace here like auth0


Also do not forget after adding new public endpoint you should add it here https://github.com/openware/barong/blob/master/config/authz_rules.yml

2021-01-25 07:21 UTC, xenirio commented
I will make updates version with the new PR. I will close this PR.

2021-01-25 07:21 UTC, closed without merging