Remove state from profile [WIP]
openware/barong pull request #435
Opened 2018-04-30 17:50 UTC by andreymakovenko

2018-05-10 07:47 UTC, tamadamas requested changes

2018-05-10 07:47 UTC, maksim-litvinov commented on app/models/document.rb
> +  def create_or_update_document_label
I can't understand why do you duplicate label logic in model and controller?

2018-05-10 07:47 UTC, maksim-litvinov commented on app/models/label.rb
> +      EventAPI.notify('system.document.verified', account_uid: account.uid)
add `TODO: Need to update specs/event_api.md` if you don't add it in current request. Specs are important for users of Events API

2018-05-10 07:47 UTC, maksim-litvinov commented on app/models/phone.rb
> +  belongs_to :account, optional: true
Why optional?

2018-05-10 07:47 UTC, maksim-litvinov commented on app/views/admin/profiles/show.html.erb
> +          <%= @profile.account.labels.find_by(key: 'document', scope: 'private')&.value %>
Never do any ActiveRecord `find, where` in a view

2018-05-10 07:47 UTC, maksim-litvinov commented on app/views/admin/profiles/show.html.erb
> +            <%= link_to(state.upcase_first, document_label_admin_profile_path(@profile, state: state), method: :put, class: 'dropdown-item') unless @profile.account.labels.find_by(key: :document).val
same as above. And use short string. It's hard to read

2018-05-10 07:47 UTC, maksim-litvinov commented on app/views/profile_review_mailer/approved.html.erb
> +      <p> Hello, <%= @profile.first_name %> <%= @profile.last_name %>!</p>
We can use just `@profile.name` here
```
class Profile
  def name
    "#{first_name} #{last_name}"
  end
end
```

2018-05-10 07:47 UTC, maksim-litvinov commented on app/views/profile_review_mailer/rejected.html.erb
> +      <p> Hello, <%= @profile.first_name %> <%= @profile.last_name %>!</p>
same as above

2018-05-10 07:47 UTC, maksim-litvinov commented on spec/models/document_spec.rb
> +        create_document
Suggest to do `expect { create_document }.to change { current_account.labels.count }.from(0).to(1)`
probably some `reload` needed

2018-05-10 07:47 UTC, maksim-litvinov commented on spec/models/document_spec.rb
> +        expect(current_account.labels.first.key).to eq 'document'
```
 let(:document_label) { current_account.labels.first }
...
expect(document_label.key).to eq 'document'
```

2018-05-10 07:47 UTC, maksim-litvinov commented on spec/models/document_spec.rb
> +        expect(current_account.labels.count).to eq 1
how do I know that next is true "does not add new label".
probably it should be expect { create_document }.to_not change { Label.count }

2018-05-10 07:47 UTC, maksim-litvinov commented on spec/models/document_spec.rb
> +        expect(current_account.labels.count).to eq 1
same as above

2018-05-10 07:47 UTC, maksim-litvinov commented on spec/models/document_spec.rb
> +        expect(current_account.labels.first.value).to eq 'verified'
same as above

2018-05-10 07:47 UTC, maksim-litvinov commented on spec/models/label_spec.rb
> +      let(:mailer_deliveries) { ActionMailer::Base.deliveries }
why not `let(:last_mailer_delivery) { ActionMailer::Base.deliveries.last }`

2018-05-10 07:47 UTC, maksim-litvinov commented on spec/models/label_spec.rb
> +          expect(account.labels.first).to eq label_public
`expect(account.labels).to eq [label_public, label_private]`

2018-05-10 07:47 UTC, maksim-litvinov commented on spec/models/label_spec.rb
> +    context 'with public labels duplicating levels' do
Wrong name. It's not implicit reason for spec.
I suggest `when account has all required label for level 4 but in public scope`

2018-05-14 07:06 UTC, tamadamas approved these changes

2018-05-15 13:04 UTC, maksim-litvinov commented
already merged with #460 branch

2018-05-15 13:04 UTC, closed without merging