GeeTest.com captcha integration on Barong v2
openware/barong pull request #665
Opened 2018-12-02 22:10 UTC by bodiasuprun

2018-12-03 09:23 UTC, ec commented
related to PR

https://github.com/bodiasuprun/geetest-ruby

2018-12-03 15:13 UTC, ec commented
So, the plan now is more clear:

We should have a configuration `captcha_policy` with 3 parameters
> disabled
> geetest_captcha
> re_captcha

Depending on that we can improve our verify and API parameters logic.
See the comments on commit for detailed plan

2018-12-03 15:19 UTC, ec requested changes

2018-12-03 15:19 UTC, ec commented on app/api/v2/identity/sessions.rb
> +          optional :geetest_response, type: Hash do
Here we can leave only optional `:captcha_response, type: any`
No need to specify exact type and requires, as we dont need the captcha type at this point

2018-12-03 15:19 UTC, ec commented on app/api/v2/identity/sessions.rb
> +          verify_geetest!(response: params['geetest_response']) if declared_params[:geetest_response]
here should be helper method `verify_captcha`
In the helpers file (utils.rb) you can check the configuration.
> skip if disabled
>  if its recaptcha - call recaptcha_verifier
>  if its geetest -  check if all the params are present (challenge, validate, seccode) and call geetest verifier

2018-12-03 15:19 UTC, ec commented on app/api/v2/identity/users.rb
> +          optional :recaptcha_response, type: String, desc: 'Response from Recaptcha widget'
here is the same

2018-12-03 15:19 UTC, ec commented on app/api/v2/identity/users.rb
> +          GeetestVerifier.new.register()
Should be in helpers and executed automatically if its geetest

2018-12-03 15:19 UTC, ec commented on app/services/geetest_verifier.rb
> +class GeetestVerifier
We should look for the opportunity to merge both types of captcha in one service file

2018-12-03 15:19 UTC, ec commented on app/services/geetest_verifier.rb
> +    @geetest_key = ENV['GEETEST_KEY']
This secrets should go to barong secret storage. Look over the app to see an example

2018-12-04 00:24 UTC, bsuprun commented
TODO: fix tests

2018-12-04 12:42 UTC, ec approved these changes

2018-12-17 09:32 UTC, ec commented
Merge branch into master commit should be inside the PR

2018-12-17 14:56 UTC, merged