Add ability to upload multiple documents
openware/barong pull request #679
Opened 2018-12-05 21:42 UTC by alinetskyi

2018-12-06 08:49 UTC, ec requested changes

2018-12-06 08:49 UTC, ec commented on app/api/v2/resource/documents.rb
> +        #rescue Excon::Error => e
what is the purpose of commented rescue?

2018-12-06 08:49 UTC, ec commented on spec/api/v2/resource/documents_spec.rb
> +      binding.pry
you forgot binding

2018-12-06 11:46 UTC, ec approved these changes

2018-12-07 00:38 UTC, mod approved these changes

2018-12-10 00:03 UTC, merged