Added event API documentation with examples
openware/barong pull request #745
Opened 2019-01-28 10:27 UTC by ec

closes #735

2019-01-28 15:55 UTC, shal approved these changes

2019-02-01 11:49 UTC, mod requested changes

2019-02-01 11:49 UTC, mod commented on app/api/v2/identity/users.rb
> +            EventAPI.notify('system.user.password.reseted', current_user.as_json_for_event_api)
reset in the past is reset too
I don't mind the convention that was before using present everywhere

2019-02-06 18:21 UTC, mod requested changes

2019-02-06 18:21 UTC, mod commented on app/api/v2/identity/users.rb
> +            EventAPI.notify('system.user.password.reseted', current_user.as_json_for_event_api)
rename to present time

2019-02-07 11:36 UTC, merged