[WIP] Activity rework
openware/barong pull request #835
Opened 2019-05-27 13:22 UTC by ec

2019-06-07 11:37 UTC, pkucherenk0 commented
I have seeded next permissions to all admin roles:
```
 - { role: superadmin, verb: get, path: admin, action: audit }
 - { role: superadmin, verb: post, path: admin, action: audit }
 - { role: superadmin, verb: put, path: admin, action: audit }
 - { role: superadmin, verb: delete, path: admin, action: audit }
 - { role: superadmin, verb: get, path: api/v2, action: audit }
 - { role: superadmin, verb: post, path: api/v2, action: audit }
 - { role: superadmin, verb: put, path: api/v2, action: audit }
 - { role: superadmin, verb: delete, path: api/v2, action: audit }
```

By calling to  `{{barong}}admin/activities/admin`  was able to get **only** activity related to `"action": "list"` (that`s requesting metrics, list of users ...) and it was not consistent. 

Creating role with api  `{{barong}}admin/permissions` had the same zero effect on admin activity logs.

2019-06-07 11:42 UTC, ec commented
@pkucherenk0 let's pair on it at Monday and check together.
Probably, I will need to add and will add a MD file explaining the whole process

2019-06-10 10:18 UTC, pkucherenk0 commented
Fix the seed.rb so we permissions with same role, verb and path but with different action and topic was seeded.

2019-06-13 06:42 UTC, calj approved these changes

2019-06-13 13:16 UTC, mod requested changes

2019-06-13 13:16 UTC, mod commented on db/schema.rb
> +    t.string "target_uuid"
t.string "source_uid"
t.string "target_uid"

2019-06-13 13:16 UTC, mod commented on lib/barong/seed.rb
> +        if Permission.find_by(role: perm["role"], verb: perm["verb"], path: perm["path"], action: perm["action"]).present?
convert all into 5 inserts

2019-06-13 13:16 UTC, mod commented on lib/barong/authorize.rb
> +        user_ip: @request.ip,
this ip is the ip from proxy
XFORWARDED_FOR

2019-06-13 13:16 UTC, mod commented on lib/barong/authorize.rb
> +        if actions.include?('AUDIT')
ALWAYS LOG DROP and permissions denied with result "denied"

2019-06-13 18:22 UTC, mod approved these changes

2019-06-13 18:22 UTC, merged