Add verb PATCH and ALL to available verbs for admin audit
openware/barong pull request #870
Opened 2019-07-15 13:01 UTC by chumaknadya

2019-07-15 13:49 UTC, ec requested changes

2019-07-15 13:49 UTC, ec commented on app/api/v2/admin/permissions.rb
>              optional :req_type,
should be named `:verb`
There is no such field `req_type` in DB
And add a test for that, please

2019-07-15 14:15 UTC, ec approved these changes

2019-07-16 11:21 UTC, mod approved these changes

2019-07-16 11:22 UTC, merged