Add validation for referral && Add ability to get referral uid
openware/barong pull request #882
Opened 2019-07-29 14:58 UTC by chumaknadya

2019-07-29 15:06 UTC, ec requested changes

2019-07-29 15:06 UTC, ec commented on app/models/user.rb
> +    user = User.find_by(id: referral_id)
can be compacted into one-line-function

2019-07-29 15:06 UTC, ec commented on app/models/user.rb
> +    errors.add(:referral_id, 'doesnt exist') if referral_id.present? && User.find_by(id: referral_id).blank?
we use dictionary errors, so `doesnt_exist` or just `exist` - it will point FE with translations

2019-07-29 15:06 UTC, ec commented on app/api/v2/entities/user_with_full_info.rb
> +        expose :referral_uid, documentation: { type: 'String' } do |user|
better to have `desc:` here, as it's a bit unclear place

2019-07-29 15:06 UTC, ec commented on app/models/user.rb
> +  def referral_exists
to have comment on top of function here will be great

2019-07-30 16:12 UTC, ec approved these changes

2019-08-19 13:38 UTC, mod approved these changes

2019-08-19 13:38 UTC, merged