Add session autorenew
openware/barong pull request #903
Opened 2019-08-22 14:18 UTC by dnfd

2019-08-22 14:25 UTC, ec requested changes

2019-08-22 14:25 UTC, ec commented on config/initializers/barong.rb
> +  config.set(:session_auto_renew, false)
value should be in strings
lets stick to 'enabled' and 'disabled'

also var name should be prefixed with 'barong'

2019-08-28 02:53 UTC, ec commented
This patch is conflicting with validations patch. Lets wait until we merge #904 first

2019-08-28 02:53 UTC, ec approved these changes

2019-09-18 14:12 UTC, ec approved these changes

2019-09-18 16:51 UTC, mod requested changes
I don't agree with having a param
To me this should work well out of the box
What's the usecase ?
What are the API calls which triggers renew

More important is security like redis session and CSRF token on login

2019-09-20 11:58 UTC, merged