Add script, which can be used for JS, Ruby and Golang projects
openware/barong pull request #905
Opened 2019-08-26 14:18 UTC by Anna-Kulakova

2019-08-27 03:54 UTC, mnaichuk commented on bin/bump.sh
> +    #git remote add authenticated-origin https://github.com/Kohelbekker/barong
remove this line please.

2019-08-28 07:38 UTC, ec requested changes
@Anna-Kulakova https://ci.microkube.com/rubykube/barong/1008
This error means you are not rebased on the latest master.
Please rebase PR on master and drone will get up)

2019-08-28 07:55 UTC, ec approved these changes

2019-09-03 06:47 UTC, ec commented
@Anna-Kulakova are guys still testing some stuff?
Can i freeze PR?

2019-09-03 06:50 UTC, ec commented
let me know if you need to reopen it

2019-11-04 16:35 UTC, closed without merging