[WIP] Prepare more flexible signup flow
openware/barong pull request #907
Opened 2019-08-28 02:40 UTC by ec

2019-08-28 10:28 UTC, mod commented
- [ ] Remove discared and put locked
- [ ] Label are not limited to :verified we can define scope=system
- [ ] move data field and allow json and max 1MB
- [ ] Publish data in entity, remove extended user profile, default api is always extended
- [ ] locked example label suspicious:trade suspicious:deposit

2019-08-28 10:32 UTC, mod commented
```
user_state
  requirements:
    active:
      email: 'verified'
      phone: 'verified'
  mapping:
    locked:
       suspicious:trade
       suspicious:deposit
```

2019-08-28 10:35 UTC, mod commented
```
user_state:
  active:
    require: all
      - email: 'verified'
      - phone: 'verified'
    locked: any
       - suspicious: 'trade'
       - suspicious: 'deposit'
```

2019-08-29 03:33 UTC, ec commented
I suggest to have a module structure:
   module all
      state
      state
  module any
      state
      state

Looks more readable in code and not so bad in yml
```
user_state:
  all:
    active:
      email: 'verified'
      phone: 'verified'
    banned:
      ban: 'weneedtochoose'
    deleted:
      deleted: 'weneedtochoose'
  any:
    locked:
      suspicious: 'trade'
      suspicious: 'deposit'
```

2019-09-02 10:38 UTC, mod requested changes

2019-09-02 10:38 UTC, mod commented on app/api/v2/admin/users.rb
> +              target_user.add_private_label('ban', 'weneedtochoose')
I'd rather not chooose; why is this necessary ?

2019-09-02 10:38 UTC, mod commented on config/user_state_requirements.yml
> +      suspicious: 'deposit'
config/barong.yml
```
activation_requirements:
      email: 'verified'
      phone: 'verified'
state_triggers:
    banned:
      - ban
      - fraud
    deleted:
      - delete
    locked:
      - suspicious
      - lock
feature_xyz:
  settings:
     sdfkljdlkfgj: 24
```

later:
barong.state_triggers.banned = [ban, fraud]
app_name . component . key = value

fraud:trade
fraud:deposit
fraud:*

2019-09-03 06:02 UTC, mod commented on app/api/v2/resource/users.rb
> +          current_user.labels.create(key: 'deleted', value: 'by_user', scope: 'private')
delete:by_user

2019-09-03 06:02 UTC, mod commented on app/models/user.rb
> +  validates :data, data_prefix: true
remove data_prefix: true

2019-09-03 06:06 UTC, mod requested changes
almost ready for merge

2019-09-03 06:06 UTC, mod commented on app/models/user.rb
> +
#FIXME BarongConfig should be a feature of Barong::App
A good name for Barong::App can be Barong::Config and we can add database support or vault based configs.

2019-09-03 06:06 UTC, mod commented on config/initializers/barong_config.rb
> +class BarongConfig
FIXME Move to barong.rb later

2019-09-03 06:44 UTC, merged