Change twilio API
openware/barong pull request #908
Opened 2019-08-28 14:09 UTC by chumaknadya

2019-08-28 16:21 UTC, ec requested changes

2019-08-28 16:21 UTC, ec commented on app/models/phone.rb
> +    def send_code(number:, channel:)
please extact to separate function

client = Barong::App.config.twilio_client
service_sid = Barong::App.config.twilio_service_sid

client.verify.services(service_sid)

2019-08-28 16:40 UTC, ec requested changes

2019-08-28 16:40 UTC, ec commented on Gemfile
> +gem 'twilio-ruby',  '~> 5.25.4'
Why decreasing the Twilio version?
We should find a way to work with new versions.
We can't be stuck at this version forever

2019-08-28 16:40 UTC, ec commented on app/api/v2/resource/phones.rb
> +                   values: { value: %w(sms call), message: 'resource.phone.invalid_channel'},
better we define a range of values in the model and use it everywhere, so we will not miss it anywhere, if any changes.
like `Phone::TWILIO_CHANNELS`
(think about naming)

2019-08-28 16:40 UTC, ec commented on app/api/v2/resource/phones.rb
>            { message: 'Code was sent successfully' }
Change the message, so we can understand what channel was used

2019-08-28 16:40 UTC, ec commented on app/api/v2/resource/phones.rb
> +                   values: { value: %w(sms call), message: 'resource.phone.invalid_channel'},
the same.
Do you see? Already spreading hardcoded range in 2 files.

2019-08-28 16:40 UTC, ec commented on app/api/v2/resource/phones.rb
>            { message: 'Code was sent successfully' }
message

2019-08-28 16:40 UTC, ec commented on app/api/v2/resource/phones.rb
> +          code_error!(phone.errors.details, 422) unless phone
this doesn't make any sense now.
It was an error if the phone cant be updated. And now? This is invalid

2019-08-28 16:40 UTC, ec commented on app/api/v2/resource/phones.rb
> +          current_user.phones.find_by(number: phone_number).update(validated_at: Time.current)
the problem is, that now you don't check if the user trying to validate his own phone.
We should have an assignment `current_user.phones.find_by(number: phone_number)` before doing action with twilio

2019-08-28 16:40 UTC, ec commented on app/models/phone.rb
> +      Rails.logger.info("Sending code to #{phone.number}")
the message should differ for channels. Better we now more info

2019-08-28 16:40 UTC, ec commented on app/models/phone.rb
> +      client = Barong::App.config.twilio_client
prefix configs with barong_

2019-08-28 16:40 UTC, ec commented on config/initializers/phone.rb
> +Barong::App.set(:twilio_client, client) if client
and what will happen if not `client`?
We will have errors in the project?

Better we think about this now

2019-08-28 16:43 UTC, ec commented on Gemfile
> +gem 'twilio-ruby',  '~> 5.25.4'
Uh, its 25 vs 6
Sorry)

2019-08-28 17:46 UTC, mod commented
looks more like a migration than an actual ability to switch.
I was thinking of making abstract class and config for choosing confirmation strategy

2019-08-28 17:53 UTC, ec commented
@mod are there any reasons for us not to actually `migrate` to this version of Twilio?
It is more smoothy, new, maintaining right now. 

Maybe just do a configuration file limiting channel to `SMS` only.

2019-08-28 17:55 UTC, ec commented
@mod just maintaining both is a bit difficult. And will spread garbage all over the project

2019-08-30 08:20 UTC, ec commented
will be reopened from branch soon

2019-08-30 08:20 UTC, closed without merging