Fix structure of event API messages
openware/barong pull request #912
Opened 2019-09-02 15:13 UTC by shal

2019-09-02 15:24 UTC, ec requested changes

2019-09-02 15:24 UTC, ec commented on app/models/label.rb
> +  def as_json_for_event_api
{ 
      id: id,
      user: user.as_json_for_event_api,
      key: key,
      value: value
}

2019-09-02 15:24 UTC, ec commented on docs/event_api.md
> +| `user`     | The up-to-date user attributes.     |
so, there is some "record" here, not only `user`, so please add in desctiption

2019-09-02 15:24 UTC, ec commented on docs/event_api.md
> +  record:
missing `{`

2019-09-02 15:24 UTC, ec commented on docs/event_api.md
> +fevent: {
`fevent` ?

2019-09-02 15:24 UTC, ec commented on docs/event_api.md
> +## Format of `system.document.rejected` event\
`\`

2019-09-02 15:28 UTC, shal commented on app/models/label.rb
> +  def as_json_for_event_api
why?

2019-09-05 15:23 UTC, ec approved these changes

2019-09-05 15:23 UTC, merged