Server side sessions implementation (cache store)
openware/barong pull request #949
Opened 2019-10-07 11:03 UTC by ec

2019-10-07 11:10 UTC, ec commented on Gemfile
> -
add a version

2019-10-07 11:10 UTC, ec commented on app/api/v2/identity/utils.rb
> +      def open_session(user)
think if there is a way to optimize this lines

MERGE doesnt work

2019-10-07 11:10 UTC, ec commented on config/initializers/sessions_store.rb
>  # Store sessions in cookies
modify comment

2019-10-07 11:10 UTC, ec commented on lib/barong/authorize.rb
> +    def request_params(user)
move to `private`

2019-10-07 11:10 UTC, ec commented on spec/api/v2/auth/sessions_spec.rb
> +        # expect(Rails.cache.read(session[:uid])).not_to be_nil
commented code

2019-10-07 11:10 UTC, ec commented on spec/api/v2/identity/sessions_spec.rb
> +      # TODO session expiration time checks
uncomment test, should work now

2019-10-11 09:46 UTC, mod requested changes

2019-10-11 09:46 UTC, mod commented on config/initializers/sessions_store.rb
> +Rails.application.config.session_store :cache_store, key: '_barong_session', domain: :all, tld_length: 2
add expire 24h to clean redis

2019-10-11 09:46 UTC, mod commented on config/initializers/cors.rb
> +  config.set(:api_cors_max_age, '3600')
double check you seem to fix this twice with the to_i
shouldn't it be integer again ?

2019-10-11 09:46 UTC, mod commented on spec/api/v2/auth/sessions_spec.rb
> +        binding.pry
remove

2019-10-11 09:59 UTC, ec commented on config/initializers/cors.rb
> +  config.set(:api_cors_max_age, '3600')
this one we keep as string. Previosly type integer just checked if string contains a nu,ber. Now it converts it to integer

2019-10-11 10:02 UTC, mod approved these changes

2019-10-11 10:03 UTC, merged