Feature: new drone steps for telegram notification and documents gene…
openware/barong pull request #974
Opened 2019-11-15 18:27 UTC by Kohelbekker

…ration

2019-11-18 15:19 UTC, chumaknadya requested changes

2019-11-18 15:19 UTC, chumaknadya commented on .drone.yml
> +    SDK_BRANCH: test
SDK_BRANCH=${DRONE_BRANCH}

2019-11-18 15:19 UTC, chumaknadya commented on .drone.yml
> +    - bundle exec rake ci:changelog['/drone/src/docs']
- bundle exec rake ci:changelog['/drone/src/']

2019-11-18 15:19 UTC, chumaknadya commented on .drone.yml
> +      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile sdk:notify:telegram
- BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile sdk:notify:telegram sdk:notify:slack

2019-11-18 15:19 UTC, chumaknadya commented on .drone.yml
> +      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile sdk:notify:slack
delete this line

2019-11-18 15:19 UTC, chumaknadya commented on .drone.yml
> +    BRANCH_NAME: master
BRANCH_NAME: ${DRONE_BRANCH}

2019-11-18 15:19 UTC, chumaknadya commented on .drone.yml
> +      - 2-0-stable
Please, check stable branches on barong. We don't have 2-0-stable branch on barong

2019-11-19 19:43 UTC, mod approved these changes

2019-11-19 19:43 UTC, merged